// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/TiktokCommence/authService/internal/biz"
	"github.com/TiktokCommence/authService/internal/casbin"
	"github.com/TiktokCommence/authService/internal/conf"
	"github.com/TiktokCommence/authService/internal/redis"
	"github.com/TiktokCommence/authService/internal/registry"
	"github.com/TiktokCommence/authService/internal/server"
	"github.com/TiktokCommence/authService/internal/service"
	"github.com/TiktokCommence/authService/internal/token"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, confToken *conf.Token, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	authCase := casbin.NewAuthCase(data)
	client := redis.NewRedisDB(data)
	cache := redis.NewCache(client)
	jwTer := token.NewJWTer()
	signer := biz.NewSigner(cache, jwTer, confToken)
	verifyer := biz.NewVerifier(cache, jwTer, confToken)
	authUserCase := biz.NewAuthUserCase(authCase, signer, verifyer)
	authServiceService := service.NewAuthServiceService(authUserCase)
	grpcServer := server.NewGRPCServer(confServer, authServiceService, logger)
	etcdRegistry := registry.NewRegistrarServer(confRegistry, logger)
	app := newApp(logger, grpcServer, etcdRegistry)
	return app, func() {
	}, nil
}
